# Generated by Django 3.1.2 on 2022-02-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='soldFor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
